name: Cargo Build & Test

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest - OTP ${{matrix.otp}}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        otp: ['26.2']
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
      - run: cargo test --verbose

  latest_deps:
    name: Latest Dependencies - OTP ${{matrix.otp}}
    strategy:
      matrix:
        otp: ['26.2']
    runs-on: ubuntu-20.04
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
      - run: rustup update stable && rustup default stable
      - run: cargo update --verbose
      - run: cargo build --verbose
      - run: cargo test --verbose
